a = set()
n = int ( input ( "Enter number :"))
a.add(n)
n = int ( input ( "Enter number :"))
a.add(n)
n = int ( input ( "Enter number :"))
a.add(n)
n = int ( input ( "Enter number :"))
a.add(n)
n = int ( input ( "Enter number :"))
a.add(n)
n = int ( input ( "Enter number :"))
a.add(n)
n = int ( input ( "Enter number :"))
a.add(n)
n = int ( input ( "Enter number :"))
a.add(n)

print(a)